//
//  CloseCode.swift
//
//
//  Created by Helloyunho on 2022/08/06.
//

import Foundation

public enum GatewayCloseCode: UInt16 {
    case UNKNOWN_ERROR = 4000, UNKNOWN_OPCODE, DECODE_ERROR, NOT_AUTHENTICATED, AUTHENTICATION_FAILED, ALREADY_AUTHENTICATED
    case INVALID_SEQ = 4007, RATE_LIMITED, SESSION_TIMEOUT, INVALID_SHARD, SHARDING_REQUIRED, INVALID_VERSION, INVALID_INTENT, DISALLOWED_INTENT
}

public enum VoiceCloseCode: UInt16 {
    case UNKNOWN_OPCODE = 4001, DECODE_ERROR, NOT_AUTHENTICATED, AUTHENTICATION_FAILED, ALREADY_AUTHENTICATED, SESSION_NO_LONGER_VALID
    case SESSION_TIMEOUT = 4009
    case SERVER_NOT_FOUND = 4011, UNKNOWN_PROTOCOL
    case DISCONNECTED = 4014, VOICE_SERVER_CRASHED, UNKNOWN_ENCRYPTION_MODE
}
